# Generated by Django 4.2.6 on 2024-10-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_mon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('login', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='логин')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='пароль')),
                ('date_reg', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата  регистрации')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Права на админа')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ к оплатам')),
                ('is_active', models.BooleanField(default=False, verbose_name='Доступ к авторизации')),
                ('balance', models.PositiveBigIntegerField(default=0, null=True, verbose_name='Баланс')),
                ('avail_balance', models.BigIntegerField(default=0, null=True, verbose_name='Сумма оплат')),
                ('region', models.CharField(choices=[('Чуйская', 'Чуйская'), ('Иссык-кульская', 'Иссык-кульская'), ('Нарынская', 'Нарынская'), ('Джалал-Абадская', 'Джалал-Абадская'), ('Баткенская', 'Баткенская'), ('Ошская', 'Ошская'), ('Таласская', 'Таласская')], default='Чуйская', max_length=100, verbose_name='Регион')),
                ('refill', models.BigIntegerField(default=0, null=True, verbose_name='Пополнение баланса')),
                ('write_off', models.BigIntegerField(default=0, null=True, verbose_name='Списание баланса')),
                ('comment', models.TextField(blank=True)),
                ('planup_id', models.BigIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_payment', models.CharField(max_length=100, null=True)),
                ('date_payment', models.CharField(max_length=100, null=True, verbose_name='Дата')),
                ('accept_payment', models.CharField(max_length=100, null=True)),
                ('ls_abon', models.CharField(max_length=100, null=True, verbose_name='Лицевой счет')),
                ('money', models.CharField(max_length=30, null=True, verbose_name='Сумма')),
                ('status_payment', models.CharField(max_length=100, null=True, verbose_name='Статус  оплаты')),
                ('annulment', models.BooleanField(default=False, verbose_name='Аннулирование')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='localpay.user_mon', verbose_name='Монтажник')),
            ],
            options={
                'verbose_name': 'История  платежа',
                'verbose_name_plural': 'История  платежей',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Комментарии')),
                ('type_pay', models.CharField(max_length=30, null=True, verbose_name='Тип платежа')),
                ('old_balance', models.BigIntegerField(default=0, null=True, verbose_name='До пололнения ')),
                ('new_balance', models.BigIntegerField(default=0, null=True, verbose_name='Пополненная сумма')),
                ('mont_balance', models.PositiveBigIntegerField(default=0, null=True, verbose_name='Баланс')),
                ('old_avail_balance', models.BigIntegerField(default=0, null=True, verbose_name='До списания')),
                ('new_avail_balance', models.BigIntegerField(default=0, null=True, verbose_name='Списание')),
                ('mont_avail_balance', models.BigIntegerField(default=0, null=True, verbose_name='Сумма оплат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='localpay.user_mon', verbose_name='Монтажник')),
            ],
            options={
                'verbose_name': 'Операции платежей',
                'verbose_name_plural': 'Операции платежей',
            },
        ),
    ]
