# Generated by Django 4.2.6 on 2024-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mon',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
