# Generated by Django 5.1.2 on 2024-11-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpay', '0002_user_mon_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mon',
            name='avail_balance',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Сумма оплат'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='balance',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='refill',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Пополнение баланса'),
        ),
        migrations.AlterField(
            model_name='user_mon',
            name='write_off',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Списание баланса'),
        ),
    ]
