"""BigInt -> Float in Payment model

Revision ID: 1226e8f89b02
Revises: 61e665deec6b
Create Date: 2024-07-03 10:06:06.752762

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1226e8f89b02'
down_revision: Union[str, None] = '61e665deec6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('localpay_payments', 'money',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('localpay_payments', 'money',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
