"""one more fix 2

Revision ID: 2a2cc1062a11
Revises: 2a1b403658c3
Create Date: 2024-07-02 11:19:03.140394

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a2cc1062a11'
down_revision: Union[str, None] = '2a1b403658c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
