"""one more fix 3

Revision ID: 2e9621bb3ceb
Revises: 2a2cc1062a11
Create Date: 2024-07-02 11:20:13.036124

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e9621bb3ceb'
down_revision: Union[str, None] = '2a2cc1062a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
