"""add planup_id field to user

Revision ID: 34c3357a0cb6
Revises: 518654c372b2
Create Date: 2024-07-19 11:00:22.968178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c3357a0cb6'
down_revision: Union[str, None] = '518654c372b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_users', sa.Column('planup_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('localpay_users', 'planup_id')
    # ### end Alembic commands ###
