"""add_to_spent_balance to add_to_spent_money

Revision ID: 3ddec0136fb5
Revises: fa181744fc00
Create Date: 2024-07-03 11:50:22.784278

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ddec0136fb5'
down_revision: Union[str, None] = 'fa181744fc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_comments', sa.Column('add_to_spent_money', sa.BigInteger(), nullable=True))
    op.drop_column('localpay_comments', 'add_to_spent_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_comments', sa.Column('add_to_spent_balance', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('localpay_comments', 'add_to_spent_money')
    # ### end Alembic commands ###
