"""advanced initial migration

Revision ID: 8c08fbac4d83
Revises: 
Create Date: 2024-07-02 11:07:21.598278

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c08fbac4d83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS regionenum")
    op.create_table('localpay_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('access_to_payments', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('available_balance', sa.BigInteger(), nullable=True),
    sa.Column('spent_money', sa.BigInteger(), nullable=True),
    sa.Column('region', sa.Enum('CHUY', 'ISSYK_KUL', 'NARYN', 'JALAL_ABAD', 'BATKEN', 'OSH', 'TALAS', name='regionenum'), nullable=False),
    sa.Column('refill', sa.BigInteger(), nullable=True),
    sa.Column('write_off', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localpay_users_id'), 'localpay_users', ['id'], unique=False)
    op.create_index(op.f('ix_localpay_users_login'), 'localpay_users', ['login'], unique=True)
    op.create_table('localpay_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('type_pay', sa.String(length=30), nullable=True),
    sa.Column('old_available_balance', sa.BigInteger(), nullable=True),
    sa.Column('old_spent_balance', sa.BigInteger(), nullable=True),
    sa.Column('add_to_available_balance', sa.BigInteger(), nullable=True),
    sa.Column('add_to_spent_balance', sa.BigInteger(), nullable=True),
    sa.Column('new_available_balance', sa.BigInteger(), nullable=True),
    sa.Column('new_spent_balance', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['localpay_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localpay_comments_id'), 'localpay_comments', ['id'], unique=False)
    op.create_table('localpay_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_accept', sa.DateTime(), nullable=True),
    sa.Column('ls_abon', sa.String(length=100), nullable=True),
    sa.Column('money', sa.BigInteger(), nullable=True),
    sa.Column('payment_status', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('annulment', sa.Boolean(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['localpay_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localpay_payments_id'), 'localpay_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localpay_payments_id'), table_name='localpay_payments')
    op.drop_table('localpay_payments')
    op.drop_index(op.f('ix_localpay_comments_id'), table_name='localpay_comments')
    op.drop_table('localpay_comments')
    op.drop_index(op.f('ix_localpay_users_login'), table_name='localpay_users')
    op.drop_index(op.f('ix_localpay_users_id'), table_name='localpay_users')
    op.drop_table('localpay_users')
    # ### end Alembic commands ###
