"""add new role

Revision ID: cb402f6f1257
Revises: 3ddec0136fb5
Create Date: 2024-07-11 11:23:02.601533

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cb402f6f1257'
down_revision: Union[str, None] = '3ddec0136fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roleenum = postgresql.ENUM('USER', 'ADMIN', 'SUPERVISOR', name='roleenum')
    roleenum.create(op.get_bind(), checkfirst=True)

    op.add_column('localpay_users', sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERVISOR', name='roleenum'), nullable=False))
    op.drop_column('localpay_users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('localpay_users', 'role')
    # ### end Alembic commands ###
