"""old_spent_balance to old_spent_money

Revision ID: fa181744fc00
Revises: ff8b1869f567
Create Date: 2024-07-03 11:49:13.893148

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa181744fc00'
down_revision: Union[str, None] = 'ff8b1869f567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_comments', sa.Column('old_spent_money', sa.BigInteger(), nullable=True))
    op.drop_column('localpay_comments', 'old_spent_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_comments', sa.Column('old_spent_balance', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('localpay_comments', 'old_spent_money')
    # ### end Alembic commands ###
