"""type_pay to payment_type. new_spent_balance to new_spent_money

Revision ID: ff8b1869f567
Revises: 1226e8f89b02
Create Date: 2024-07-03 11:42:10.276303

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff8b1869f567'
down_revision: Union[str, None] = '1226e8f89b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_comments', sa.Column('payment_type', sa.String(length=30), nullable=True))
    op.add_column('localpay_comments', sa.Column('new_spent_money', sa.BigInteger(), nullable=True))
    op.drop_column('localpay_comments', 'new_spent_balance')
    op.drop_column('localpay_comments', 'type_pay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localpay_comments', sa.Column('type_pay', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('localpay_comments', sa.Column('new_spent_balance', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('localpay_comments', 'new_spent_money')
    op.drop_column('localpay_comments', 'payment_type')
    # ### end Alembic commands ###
