version: '3.8'

services:
  db:
    image: postgres:16
    environment:
    - POSTGRES_DB=${POSTGRES_DB} 
    - POSTGRES_USER={POSTGRES_USER}
    - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/localpay
    ports:
      - "6433:6432"
    depends_on:
      - db

    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./userlist.txt:/etc/pgbouncer/userlist.txt:ro

  web:
    build:
      context: .
      dockerfile: ./dockerfile
    command: >
      bash -c "python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 10000 --limit-request-field_size 16384 --workers 2"

    volumes:
      - ./app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    