# основная секция для определения входных источников логов
filebeat.inputs:
  # логи будут собираться из контейнеров
- type: log
  # пути к логам которые нужно собирать 
  enabled: true  # Включаем сбор этих логов
  paths:
    - /home/vlad/erasyl_localpay/rewritten_localpay/src/user.log
  fields:
    type: user_actions
  fields_under_root: true
  json.keys_under_root: true

  # Логи платежей
- type: log
  enabled: true
  paths:
    - /home/vlad/erasyl_localpay/rewritten_localpay/src/payment.log
  fields:
    type: payment_actions
  fields_under_root: true
  json.keys_under_root: true

  # Логи мобильных пользователей
- type: log
  enabled: true
  paths:
    - /home/vlad/erasyl_localpay/rewritten_localpay/src/mobile_user_detail.log
  fields:
    type: mobile_detail
  fields_under_root: true
  json.keys_under_root: true

# логи nginx
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
  fields:
    type: nginx

# Логи Docker контейнеров
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  fields:
    type: docker

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      process_array: true
      max_depth: 10
  - add_fields:
      target: ''
      fields:
        application: localpay

# Настройка вывода в Logstash
output.logstash:
  hosts: ["10.1.4.20:5044"]

# Основные настройки логирования
logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 7
    permissions: 0644

# Мониторинг
monitoring:
  enabled: false
  cluster_uuid: "localpay-cluster"

# Метрики
xpack.monitoring:
  enabled: false

# Конфигурация перезагрузки
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

setup.template.enabled: false

setup.kibana:
  enabled: false